### ISSUE TITLE
Help with setting up publish on release

### ISSUE THREAD

**Issue by Phyore** [GreenTF/upload-thunderstore-package#32]
I followed the set up instructions as well as I think I have however I got the following error after creating a "release"
```
Configure tcli
  Init tcli config
  WARNING: Unable to find project configuration file
  Looked from /thunderstore.toml
  ERROR: Invalid configuration to run 'init' command
  Invalid package version number "release". Version numbers must follow the Major.Minor.Patch format (e.g. 1.45.320)
  Exiting
```

https://github.com/Phyore/test-lethal-modpack/actions/runs/10459752507/job/28964411620

**Comment by AnActualEmerald** [comment]
Could you re-run that workflow and check the "enable debug" box, then post those logs please? I didn't see anything obviously wrong with your configuration so I'm not sure what's up.

**Comment by Phyore** [comment]
I have re-run that!
[logs_27348010290.zip](https://github.com/user-attachments/files/16665362/logs_27348010290.zip)

**Comment by AnActualEmerald** [comment]
Okay I *think* I have an idea what's happening, I'm away from my computer right now so I can't test it myself though

Try changing this:
```yml
on: 
  release: 
    types: [published]
```

To this:
```yml
on:
  push:
    tags:
      - *.*.*
```

You'll have to delete the `v0.0.1` tag that you created for the release and recreate it but I *think* that will fix the issue. If that works I'll update the readme too.

**Comment by Phyore** [comment]
I updated it to the following as everywhere I could see showed using some quotes around it:
```on:
  push:
    tags:
      - '*'
```

Getting:
``` publish
ERROR: Unexpected response from the server while publishing package: Status code: 400 BadRequest {"community_categories":["Category skills does not exist in community riskofrain2"]} Exiting
```

**Comment by AnActualEmerald** [comment]
Oh I'm sorry I didn't notice this before, you aren't using the most recent version of the action which actually fixes that error:

```yml
- uses: GreenTF/upload-thunderstore-package@v4.2
```
Should be 
```yml
- uses: GreenTF/upload-thunderstore-package@v4.3
```

And also `actions/checkout@v3` should be updated to `actions/checkout@v4` thought that's not related to any of the issues you've been having.

**Comment by Phyore** [comment]
Just changed it and still getting: 
```
Writing /manifest.json
  Successfully built Phyore-PhyPack-0.0.4
  Publish to https://thunderstore.dev/
  Error: ERROR: Unexpected response from the server while publishing package: Status code: 400 BadRequest {"community_categories":["Category skills does not exist in community riskofrain2"]} Exiting
```

```
name: Publish Mod

# Run when a new release is... released
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Phyore # the thunderstore 'team' to publish under
          description: Test Modpack 
          token: ${{ secrets.DEV_THUNDERSTORE_SERVICE_KEY }}
          name: PhyPack # the name of the package
          dev: true
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: lethal-company
          categories: | # <-- notice this pipe character
            modpacks
```
