### ISSUE TITLE
Can't upload NEW version at all : "manifest.json non_field_errors: Package of the same namespace, name and version already exists"

### ISSUE THREAD

**Issue by SebPikPik** [GreenTF/upload-thunderstore-package#34]
Hi,

I'm trying to publish my new version to Thunderstore (lethal company) but I keep getting these errors (see at the bottom)

### Github action
```
name: Publish Package on Thunderstore

on:
  workflow_dispatch:
  push:
    branches: "fix_testPublish"
    tags:
      - '*'

env:
  description: "Tests Modding Bikininjas Sounds"
  mod_name: "BikininjasSoundsTest"
  website_url: "https://github.com/${{ github.repository }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Get latest release number
        id: latest_release # used to read version in other steps.
        run: |
          echo "release_number=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest -s | jq -r '.tag_name // empty')" >> $GITHUB_ENV
      - name: Zip files
        run: |
          7z a -tzip -mx=9 ./Releases/bikininjaSounds-${{ env.release_number }}.zip

      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Bikininjas # the thunderstore 'team' to publish under
          description: ${{ env.description }}
          token: ${{ secrets.THUNDERSTORE_SVC_API_KEY }}
          name: ${{ env.mod_name }}
          version: ${{ env.release_number }} # Use the tag as the package version
          community: lethal-company
          deps: |
            BepInEx-BepInExPack@5.4.2100
            Clementinise-CustomSounds@2.3.2
            no00ob-LCSoundTool@1.5.1
          website: "${{ env.website_url }}"
          repo: thunderstore.io
          # path: ./
          file: ./Releases/bikininjaSounds-${{ env.release_number }}.zip
          categories: | # <-- notice this pipe character
              audio
```

### Github action logs
```
Set up environment
  Move files from . to /dist
  Move README
  Move icon
Configure tcli
  Init tcli config
  WARNING: Unable to find project configuration file
  Looked from /thunderstore.toml
  Creating a new project configuration to /
  Icon found, skipping creation of default
  Readme found, skipping creation of default
  Done!
    "BepInEx-BepInExPack@5.4.2100",
    "Clementinise-CustomSounds@2.3.2",
    "no00ob-LCSoundTool@1.5.1",
    ""
  ]
    "BepInEx-BepInExPack@5.4.2100",
    "BepInEx-BepInExPack",
    "5.4.2100",
    index: 0,
    input: "BepInEx-BepInExPack@5.4.2100",
    groups: undefined
  ]
    "Clementinise-CustomSounds@2.3.2",
    "Clementinise-CustomSounds",
    "2.3.2",
    index: 0,
    input: "Clementinise-CustomSounds@2.3.2",
    groups: undefined
  ]
    "no00ob-LCSoundTool@1.5.1",
    "no00ob-LCSoundTool",
    "1.5.1",
    index: 0,
    input: "no00ob-LCSoundTool@1.5.1",
    groups: undefined
  ]
  ::warn::Empty dependency 
    "BepInEx-BepInExPack": "5.4.2100",
    "Clementinise-CustomSounds": "2.3.2",
    "no00ob-LCSoundTool": "1.5.1"
  }
  Done config edit
  icon = "./icon.png"
  outdir = "./build"
  readme = "./README.md"
  [[build.copy]]
  source = "./dist"
  target = ""
  [config]
  schemaVersion = "0.0.1"
  [package]
  containsNsfwContent = false
  description = "Tests Modding Bikininjas Sounds"
  name = "BikininjasSoundsTest"
  namespace = "Bikininjas"
  versionNumber = "0.0.7"
  websiteUrl = "https://github.com/bikininjas/lc_bikininjaSounds"
  [package.dependencies]
  BepInEx-BepInExPack = "5.4.2100"
  Clementinise-CustomSounds = "2.3.2"
  no00ob-LCSoundTool = "1.5.1"
  [publish]
  communities = ["lethal-company"]
  repository = "thunderstore.io"
  [publish.categories]
  lethal-company = ["audio"]
  riskofrain2 = ["items", "skills"]
Publish package
  Publish to https://thunderstore.io/
  Error: ERROR: Unexpected response from the server while publishing package: Status code: 400 BadRequest {"file":["manifest.json non_field_errors: Package of the same namespace, name and version already exists"]} Exiting
```
